### ISSUE TITLE
issue with strategy.js

### ISSUE THREAD

**Issue by Willzxxz** [SojebSikder/nodejs-ecommerce#10]
im getting an error 
```
/SojebSikderNodejs-ecommerce/nodejs-ecommerce/node_modules/passport-oauth2/lib/strategy.js:87
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
```

**Comment by SojebSikder** [comment]
Copy .env.example to .env and add your client id, secret, redirect uri there.

Like this:

GOOGLE_CLIENT_ID=xxxx
GOOGLE_CLIENT_SECRET=xxxx
GOOGLE_REDIRECT_URI="${APP_URL}/auth/google"

FACEBOOK_CLIENT_ID=xxx
FACEBOOK_CLIENT_SECRET=xxx
FACEBOOK_REDIRECT_URI="${APP_URL}/auth/facebook"
