### ISSUE TITLE
no stock field in product schema

### ISSUE THREAD

**Issue by wisdomose** [SojebSikder/nodejs-ecommerce#6]
![image](https://user-images.githubusercontent.com/35114555/202871386-37999b16-b00b-4853-a2a0-2d25c9fef17a.png)
add the stock field to product schema of fix this bug. It crashes the cart page

**Comment by SojebSikder** [comment]
Hi, Actually I changed stock to quantity, and then I forgot to refactor. Now fixed,
Thank you.
